inherit_from:
  - https://relaxed.ruby.style/rubocop.yml
  - node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop-rails
  - rubocop-disable_syntax

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'config/environments/*.rb'
    - 'lib/tasks/*.rake'

Style/FrozenStringLiteralComment:
  Enabled: false

### Prettier
Style:
  Enabled: false

Style/DisableSyntax:
  DisableSyntax:
#    - unless
#    - ternary
#    - safe_navigation
    - endless_methods
    - arguments_forwarding
    - numbered_parameters
#    - pattern_matching
#    - shorthand_hash_syntax
    - and_or_not
    - until
#    - percent_literals
