inherit_from:
  - https://relaxed.ruby.style/rubocop.yml
  - node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop-rails
  - rubocop-disable_syntax

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*.rb'
    - 'bin/*'

Rails:
  Enabled: True

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'
    - 'vendor/bundle'

Style/DisableSyntax:
  DisableSyntax:
#    - unless
#    - ternary
#    - safe_navigation
    - endless_methods
    - arguments_forwarding
    - numbered_parameters
#    - pattern_matching
#    - shorthand_hash_syntax
    - and_or_not
    - until
#    - percent_literals
